---
services:
  s_ui:
    image: alireza7/s-ui
    container_name: s_ui
    hostname: "psdash.xtrend.site"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
    networks:
      - sui_net
    entrypoint: "./entrypoint.sh"

networks:
  sui_net:
    driver: bridge
  
